### PR TITLE
Expose the full Vertex and Edge object in filter functions

### LINKED ISSUE #56: Filtering/subgraphing is limited to the values only
https://github.com/TU-Berlin-DIMA/flink-graph/commit/aa0eb20f5708bdc3e2439651ca7b10436bbde640#commitcomment-9245277

The following functions allow creating subgraphs by filtering:

- filterOnVertices()
- filterOnEdges()
- subgraph()

The filter function passed to these however works only on values while it may be useful to also filter by keys. Especially for Edges it may be useful to filter by source/target vertex.

### PR DESCRIPTION
**Pull request by cebe**
Expose the full Vertex and Edge object in filter functions to allow filtering
by key value:

- subgraph()
- filterOnVertices()
- filterOnEdges()

fixes #56

### CODE REVIEW

**Comment by ktzoumas** [comment]
Thank you, I think this is a good idea. Can you also change the tests in TestGraphOperations.java? Currently the project does not compile.

**Comment by cebe** [comment]
Sure, will do.

**Comment by cebe** [comment]
I have updated the test classes, all should be fine now.

**Comment by vasia** [comment]
Hi @cebe! Thanks a lot for this contribution! Will merge :)

**Pull request merged**
